(defun day01-a (filename)
  (with-open-file (stream filename)
    (do ((floor 0)
         (c (read-char stream)
            (read-char stream nil)))
        ((null c) floor)
      (when (eq #\( c)
        (incf floor))
      (when (eq #\) c)
        (decf floor)))))

(defun day01-b (filename)
  (with-open-file (stream filename)
    (do ((pos 1
              (incf pos))
         (floor 0)
         (c (read-char stream)
            (read-char stream nil)))
        ((null c) :never)
      (when (eq #\( c)
        (incf floor))
      (when (eq #\) c)
        (decf floor))
      (when (< floor 0)
        (return pos)))))
